language: python
matrix:
  include:
    - python: 2.7
      env:
        - TOX_ENV=py27
    - python: 3.4
      env:
        - TOX_ENV=py34
    - python: 3.5
      env:
        - TOX_ENV=py35
    - python: 3.6
      env:
        - TOX_ENV=py36
    - python: 3.7
      env:
        - TOX_ENV=py37
      dist: xenial
      sudo: true
      
install:
  - pip install tox 
script:
  - tox -e $TOX_ENV

deploy:
      provider: script
      script: bash .travis/deploy.sh 
      on:
        all_branches: true
        python: 3.7
        env: TOX_ENV=py37
env:
  global:
    secure: "PjHUixnHrQUr25yDV4/hTMy2odhO3WiXchkquVV0YTF3BPCtbBjELOMlYpm/OOeKkrg4AvPSLfw4qtbifud9NpdMsrijZ98jNTEYTy7J5egLlJTy1fCKxwiPf5mO2eoHmjQqZVetu/JzLcptCbj9bci/yNtNyM/lSSegLVHsO04="
    # TEST
    secure: "l5jh2YEJCNbxXvmLOoiQTGWW9KAIyZmAH3v5Qs7h4sfQ7SwG2ysuoZ5YKzVredTXnVEZ6+jaLacCowndwi3Ae23xZlynvqWWB8JZUyw5cMAL6lgR+MjUSSu39Og1L+VWkPYe17ChDRhsR/4f9wKYS24RG8UMI1g9RUcbbrNrqbY="
